name: "RELEASE_ENABLE_MTE_ALL_BUILDS"
namespace: "pixel_gsc"
description: "Enables MTE in the build"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
