name:  "RELEASE_ZUMAPRO_TARGET_ARCH_VARIANT_ARMV87"
namespace:  "system_performance"
description:  "Build code for Tensor G4 (Zuma Pro) as ARMv8.7-A instead of ARMv8.2-A"
value: {
  bool_value: false
}
workflow:  LAUNCH
containers:  "product"
containers:  "system"
containers:  "system_ext"
containers:  "vendor"
