name:  "RELEASE_RUST_USE_ARM_TARGET_ARCH_VARIANT"
namespace:  "system_performance"
description:  "Use all ARM instructions enabled by TARGET_ARCH_VARIANT in Rust code."
value: {
  bool_value: false
}
workflow:  LAUNCH
containers:  "product"
containers:  "system"
containers:  "system_ext"
containers:  "vendor"
